import { generateRandomUnixTimestamps } from '../src/utils/datetime';
import { InboxMessages } from './db';

const timestamps = generateRandomUnixTimestamps(Math.floor(new Date().getTime() / 1000), 40);

export const INBOX_MESSAGES: InboxMessages[] = [
  {
    id: '1',
    sender: 'Gov.sg',
    body: 'Immigration & Checkpoints Authority (ICA)\n\nDear LIN JUN JIE (S****187D),\n\nICA will be calling you today between 1pm and 3pm about your PR application #PRA223101. We request your availability during this period.\n\nThis is an automated message from the Government of Singapore. Please do not reply. Immigration & Checkpoints Authority (ICA)\n\n\n\nLong Message Test:\n\n\n\nDear LIN JUN JIE (S****187D),\n\nICA will be calling you today between 1pm and 3pm about your PR application #PRA223101. We request your availability during this period.\n\nThis is an automated message from the Government of Singapore. Please do not reply Immigration & Checkpoints Authority (ICA)\n\nDear LIN JUN JIE (S****187D),\n\nICA will be calling you today between 1pm and 3pm about your PR application #PRA223101. We request your availability during this period.\n\nThis is an automated message from the Government of Singapore. Please do not reply Immigration & Checkpoints Authority (ICA)\n\nDear LIN JUN JIE (S****187D),\n\nICA will be calling you today between 1pm and 3pm about your PR application #PRA223101. We request your availability during this period.\n\nThis is an automated message from the Government of Singapore. Please do not reply Immigration & Checkpoints Authority (ICA)\n\nDear LIN JUN JIE (S****187D),\n\nICA will be calling you today between 1pm and 3pm about your PR application #PRA223101. We request your availability during this period.\n\nThis is an automated message from the Government of Singapore. Please do not reply',
    date: timestamps[0],
    isRead: false,
  },
  {
    id: '2',
    sender: 'Gov.sg',
    body: 'Housing & Development Board (HDB)\n\nDear LIN JUN JIE (S****187D),\n\nYour HDB appointment is scheduled on 18/10/2021 at 10:00 AM. Please be punctual.\n\nThis is an automated message from the Government of Singapore. Please do not reply.',
    date: timestamps[1],
    isRead: false,
  },
  {
    id: '3',
    sender: 'Gov.sg',
    body: 'Ministry of Health (MOH)\n\nDear Residents,\n\nCOVID-19 vaccination slots are now available for all eligible residents. Book your appointment today at a nearby vaccination center.\n\nThis is an automated message from the Government of Singapore. Please do not reply.',
    date: timestamps[2],
    isRead: false,
  },
  {
    id: '4',
    sender: 'Gov.sg',
    body: 'Singapore Police Force (SPF)\n\nDear Citizens,\n\nPlease be aware of the recent increase in scam calls. Do not share personal information over the phone. Report any suspicious activity to your local police station.\n\nThis is an automated message from the Government of Singapore. Please do not reply.',
    date: timestamps[3],
    isRead: false,
  },
  {
    id: '5',
    sender: 'Gov.sg',
    body: 'National Environment Agency (NEA)\n\nDear Residents,\n\nThe air quality index in your area is currently at a healthy level. Enjoy the fresh air and stay safe.\n\nThis is an automated message from the Government of Singapore. Please do not reply.',
    date: timestamps[4],
    isRead: true,
  },
  {
    id: '6',
    sender: 'Gov.sg',
    body: 'Ministry of Education (MOE)\n\nDear Parents,\n\nSchools will be reopening on schedule. Ensure your child is prepared for a safe return to the classroom.\n\nThis is an automated message from the Government of Singapore. Please do not reply.',
    date: timestamps[5],
    isRead: true,
  },
  {
    id: '7',
    sender: 'Gov.sg',
    body: 'Inland Revenue Authority of Singapore (IRAS)\n\nDear Taxpayer,\n\nThe deadline for filing your income tax returns is approaching. Ensure timely submission to avoid penalties.\n\nThis is an automated message from the Government of Singapore. Please do not reply.',
    date: timestamps[6],
    isRead: true,
  },
  {
    id: '8',
    sender: 'Gov.sg',
    body: 'Ministry of Transport (MOT)\n\nDear Commuters,\n\nThe new public transportation schedule is now in effect. Plan your daily commute accordingly.\n\nThis is an automated message from the Government of Singapore. Please do not reply.',
    date: timestamps[7],
    isRead: true,
  },
  {
    id: '9',
    sender: 'Gov.sg',
    body: "National Parks Board (NParks)\n\nDear Nature Enthusiasts,\n\nJoin us for a guided nature walk this weekend at the Botanic Gardens. Explore the beauty of Singapore's flora and fauna.\n\nThis is an automated message from the Government of Singapore. Please do not reply.",
    date: timestamps[8],
    isRead: false,
  },
  {
    id: '10',
    sender: 'Gov.sg',
    body: 'Ministry of Finance (MOF)\n\nDear Businesses,\n\nThe latest economic stimulus package is available to support your company during these challenging times. Visit our website for details.\n\nThis is an automated message from the Government of Singapore. Please do not reply.',
    date: timestamps[9],
    isRead: false,
  },
  {
    id: '11',
    sender: 'Gov.sg',
    body: 'Singapore Tourism Board (STB)\n\nDear Travelers,\n\nPlan your next staycation in Singapore and explore our vibrant city. Check out the latest promotions on our website.\n\nThis is an automated message from the Government of Singapore. Please do not reply.',
    date: timestamps[10],
    isRead: true,
  },
  {
    id: '12',
    sender: 'Gov.sg',
    body: 'Ministry of Social and Family Development (MSF)\n\nDear Families,\n\nSupport programs for families in need are available. Contact our social services hotline for assistance.\n\nThis is an automated message from the Government of Singapore. Please do not reply.',
    date: timestamps[11],
    isRead: false,
  },
  {
    id: '13',
    sender: 'Gov.sg',
    body: 'Central Provident Fund Board (CPF)\n\nDear Members,\n\nEnsure your CPF account is up to date. Log in to your account for the latest information.\n\nThis is an automated message from the Government of Singapore. Please do not reply.',
    date: timestamps[12],
    isRead: false,
  },
  {
    id: '14',
    sender: 'Gov.sg',
    body: 'Ministry of Trade and Industry (MTI)\n\nDear Entrepreneurs,\n\nExplore opportunities in the growing digital economy. Attend our upcoming webinar on digital transformation.\n\nThis is an automated message from the Government of Singapore. Please do not reply.',
    date: timestamps[13],
    isRead: true,
  },
  {
    id: '15',
    sender: 'Gov.sg',
    body: 'Agri-Food & Veterinary Authority of Singapore (AVA)\n\nDear Food Business Owners,\n\nEnsure food safety and hygiene standards in your establishments. Regular inspections will be conducted.\n\nThis is an automated message from the Government of Singapore. Please do not reply.',
    date: timestamps[14],
    isRead: true,
  },
  {
    id: '16',
    sender: 'Gov.sg',
    body: 'Ministry of Home Affairs (MHA)\n\nDear Residents,\n\nStay vigilant and report any suspicious activities in your neighborhood. Together, we can keep Singapore safe.\n\nThis is an automated message from the Government of Singapore. Please do not reply.',
    date: timestamps[15],
    isRead: false,
  },
  {
    id: '17',
    sender: 'Gov.sg',
    body: 'National Library Board (NLB)\n\nDear Readers,\n\nExplore our latest collection of books and resources available at your nearest library branch. Knowledge is power.\n\nThis is an automated message from the Government of Singapore. Please do not reply.',
    date: timestamps[16],
    isRead: false,
  },
  {
    id: '18',
    sender: 'Gov.sg',
    body: 'Ministry of Manpower (MOM)\n\nDear Employers,\n\nStay updated on labor laws and regulations. Visit our website for important employment updates.\n\nThis is an automated message from the Government of Singapore. Please do not reply.',
    date: timestamps[17],
    isRead: false,
  },
  {
    id: '19',
    sender: 'Gov.sg',
    body: 'Civil Aviation Authority of Singapore (CAAS)\n\nDear Travelers,\n\nEnsure a smooth journey by checking flight schedules and safety guidelines before your trip.\n\nThis is an automated message from the Government of Singapore. Please do not reply.',
    date: timestamps[18],
    isRead: false,
  },
  {
    id: '20',
    sender: 'Gov.sg',
    body: 'Ministry of Defence (MINDEF)\n\nDear Servicemen and Women,\n\nThank you for your service to Singapore. Your dedication is appreciated.\n\nThis is an automated message from the Government of Singapore. Please do not reply.',
    date: timestamps[19],
    isRead: false,
  },
  {
    id: '21',
    sender: 'Gov.sg',
    body: 'Ministry of Education (MOE)\n\nDear Students and Parents,\n\nThe new school term starts on 4/01/2023. Please ensure that all required textbooks and stationery are prepared. Have a great academic year!\n\nThis is an automated message from the Government of Singapore. Please do not reply.',
    date: timestamps[20],
    isRead: true,
  },
  {
    id: '22',
    sender: 'Gov.sg',
    body: 'Singapore Police Force (SPF)\n\nDear Residents,\n\nJoin us for a community safety seminar on 10/11/2022, 2:00 PM, at the community center. Learn how to keep your neighborhood secure.\n\nThis is an automated message from the Government of Singapore. Please do not reply.',
    date: timestamps[21],
    isRead: true,
  },
  {
    id: '23',
    sender: 'Gov.sg',
    body: 'Ministry of Finance (MOF)\n\nDear Taxpayer,\n\nThe tax filing deadline is approaching. Ensure your tax returns are submitted by 31/03/2023 to avoid penalties.\n\nThis is an automated message from the Government of Singapore. Please do not reply.',
    date: timestamps[22],
    isRead: true,
  },
  {
    id: '24',
    sender: 'Gov.sg',
    body: 'Singapore Health Promotion Board (HPB)\n\nDear Residents,\n\nStay healthy! Schedule your annual health checkup at the nearest HPB clinic. Early detection saves lives.\n\nThis is an automated message from the Government of Singapore. Please do not reply.',
    date: timestamps[23],
    isRead: true,
  },
  {
    id: '25',
    sender: 'Gov.sg',
    body: 'Ministry of Transport (MOT)\n\nDear Commuters,\n\nExpect delays on the East-West Line tomorrow due to track maintenance. Plan your journey accordingly.\n\nThis is an automated message from the Government of Singapore. Please do not reply.',
    date: timestamps[24],
    isRead: true,
  },
  {
    id: '26',
    sender: 'Gov.sg',
    body: 'Singapore Tourism Board (STB)\n\nDear Tourists,\n\nExplore the vibrant culture and attractions of Singapore. Check out our latest travel recommendations and offers.\n\nThis is an automated message from the Government of Singapore. Please do not reply.',
    date: timestamps[25],
    isRead: true,
  },
  {
    id: '27',
    sender: 'Gov.sg',
    body: "Ministry of Manpower (MOM)\n\nDear Employers,\n\nEnsure your employees' safety at work. Conduct regular safety briefings and inspections.\n\nThis is an automated message from the Government of Singapore. Please do not reply.",
    date: timestamps[26],
    isRead: true,
  },
  {
    id: '28',
    sender: 'Gov.sg',
    body: 'Singapore Customs\n\nDear Importers and Exporters,\n\nImportant customs update: New tariff rates will go into effect on 01/12/2022. Please review and adjust your shipments accordingly.\n\nThis is an automated message from the Government of Singapore. Please do not reply.',
    date: timestamps[27],
    isRead: true,
  },
  {
    id: '29',
    sender: 'Gov.sg',
    body: 'Ministry of Social and Family Development (MSF)\n\nDear Families,\n\nLearn about available support programs for families in need. Visit our website for more information.\n\nThis is an automated message from the Government of Singapore. Please do not reply.',
    date: timestamps[28],
    isRead: true,
  },
  {
    id: '30',
    sender: 'Gov.sg',
    body: "National Parks Board (NParks)\n\nDear Nature Enthusiasts,\n\nExplore Singapore's beautiful parks and nature reserves this weekend. Enjoy the great outdoors!\n\nThis is an automated message from the Government of Singapore. Please do not reply.",
    date: timestamps[29],
    isRead: true,
  },
  {
    id: '31',
    sender: 'Gov.sg',
    body: 'Singapore Immigration & Checkpoints Authority (ICA)\n\nDear Residents,\n\nStay informed about the latest visa regulations and entry requirements. Visit our website for updates.\n\nThis is an automated message from the Government of Singapore. Please do not reply.',
    date: timestamps[30],
    isRead: true,
  },
  {
    id: '32',
    sender: 'Gov.sg',
    body: 'Ministry of Trade and Industry (MTI)\n\nDear Business Owners,\n\nExplore government grants and support programs to boost your business. Visit our business portal for details.\n\nThis is an automated message from the Government of Singapore. Please do not reply.',
    date: timestamps[31],
    isRead: true,
  },
  {
    id: '33',
    sender: 'Gov.sg',
    body: 'Singapore Land Authority (SLA)\n\nDear Property Owners,\n\nImportant notice: Property tax assessment for the upcoming year will be sent to your registered address.\n\nThis is an automated message from the Government of Singapore. Please do not reply.',
    date: timestamps[32],
    isRead: true,
  },
  {
    id: '34',
    sender: 'Gov.sg',
    body: 'Ministry of the Environment and Water Resources (MEWR)\n\nDear Residents,\n\nHelp conserve water. Check for leaks and fix them promptly. Every drop counts.\n\nThis is an automated message from the Government of Singapore. Please do not reply.',
    date: timestamps[33],
    isRead: true,
  },
  {
    id: '35',
    sender: 'Gov.sg',
    body: 'Singapore Economic Development Board (EDB)\n\nDear Investors,\n\nDiscover investment opportunities in Singapore. Contact us for a personalized consultation.\n\nThis is an automated message from the Government of Singapore. Please do not reply.',
    date: timestamps[34],
    isRead: true,
  },
  {
    id: '36',
    sender: 'Gov.sg',
    body: "Ministry of Culture, Community, and Youth (MCCY)\n\nDear Community Leaders,\n\nJoin us for a town hall meeting on 15/12/2022, 7:00 PM, at the community center. Let's discuss community development.\n\nThis is an automated message from the Government of Singapore. Please do not reply.",
    date: timestamps[35],
    isRead: true,
  },
  {
    id: '37',
    sender: 'Gov.sg',
    body: 'Singapore Central Provident Fund (CPF)\n\nDear CPF Members,\n\nStay updated on your retirement savings. Log in to your CPF account to view your latest contributions.\n\nThis is an automated message from the Government of Singapore. Please do not reply.',
    date: timestamps[36],
    isRead: true,
  },
  {
    id: '38',
    sender: 'Gov.sg',
    body: 'Ministry of National Development (MND)\n\nDear Residents,\n\nWe value your feedback. Share your thoughts on neighborhood development in our online survey.\n\nThis is an automated message from the Government of Singapore. Please do not reply.',
    date: timestamps[37],
    isRead: true,
  },
  {
    id: '39',
    sender: 'Gov.sg',
    body: 'Singapore National Arts Council (NAC)\n\nDear Arts Enthusiasts,\n\nExplore upcoming cultural events and art exhibitions in Singapore. Embrace the arts!\n\nThis is an automated message from the Government of Singapore. Please do not reply.',
    date: timestamps[38],
    isRead: true,
  },
  {
    id: '40',
    sender: 'Gov.sg',
    body: 'Ministry of Defence (MINDEF)\n\nDear NSmen,\n\nReminder: Attend your NS reservist training on the scheduled dates. Stay prepared.\n\nThis is an automated message from the Government of Singapore. Please do not reply.',
    date: timestamps[39],
    isRead: true,
  },
];
